import java.util.Comparator;
import java.util.Objects;

/**
 * Class Product used for generating statistics. All products have a name, a price and units sold.
 * I created custom comparators by units and income generated by sales.
 * HashMap from statistics is looking only by product's name.
 */

public class Product {

    private String name;
    private int price;
    private int soldunits;

    public Product(String name) {
        this.name = name;
    }

    void addPrice (int price) { this.price += price; }

    void addSoldUnits (int soldunits) { this.soldunits += soldunits; }

    String getName() {
        return name;
    }

    int getPrice() {
        return price;
    }

    int getSoldunits() {
        return soldunits;
    }

    @Override
    public String toString() {
        return "Product{" +
                "name='" + name + '\'' +
                ", price=" + price +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Product product = (Product) o;
        return price == product.price &&
                Objects.equals(name, product.name);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, price);
    }

    static Comparator<Product> bySoldUnits = (p1, p2) -> {
        Integer Product1 = p1.getSoldunits();
        Integer Product2 = p2.getSoldunits();
        //descending order
        return Product2.compareTo(Product1);
    };

    static Comparator<Product> byIncome = (p1, p2) -> {
        Integer Product1 = p1.getPrice();
        Integer Product2 = p2.getPrice();
        //descending order
        return Product2.compareTo(Product1);
    };
}
